# Generated by Django 4.2 on 2023-04-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_prudoto_category_prudotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='prudotos',
            new_name='produtos',
        ),
    ]
